### PR TITLE
Fixed set_print_gridlines and set_display_gridlines return value

### PR DESCRIPTION
**Pull request by ghost**
test.sheet.py runs now without errors.

### CODE REVIEW

**Comment by qustavo** [comment]
which libxl version are you using ?

**Comment by qustavo** [comment]
@nahody, about 76236c0
- please, add a test case
- I would use true, for setting an XML book, but as an optional parameter
- update docs
- keep indentations
- make a different pull request

**Comment by ghost** [comment]
Ok I will do

**Comment by qustavo** [comment]
:smiley: cool!

**Comment by ghost** [comment]
So the first part is ready. I add the file format which is now not required. Default is xls. Also made required changes to enable compilation with libxl 3.5.4 and improve the tests units.
As next I will add the new functions of 3.5.4.

**Comment by ghost** [comment]
So I'm ready now. Close this request and create new one.

**Pull request closed without merging**
